x264_arg_lst= ['--keyint', '--min-keyint', '--no-scenecut',
    '--scenecut', '--intra-refresh', '--bframes', '--b-adapt', '--b-bias', '--b-pyramid', '--open-gop',
    '--no-cabac', '--ref', '--no-deblock', '--deblock', '--slices', '--slices-max', '--slice-max-size',
    '--slice-max-mbs', '--slice-min-mbs', '--tff', '--bff', '--constrained-intra', '--pulldown', '--fake-interlaced',
    '--frame-packing', '--qp', '--bitrate', '--crf', '--rc-lookahead', '--crf-max', '--qpmin', '--qpmax', '--qpstep', '--ratetol', '--ipratio', '--pbratio',
    '--chroma-qp-offset', '--aq-mode', '--aq-strength', '--pass', '--stats', '--no-mbtree', '--qcomp',
    '--cplxblur', '--qblur', '--zones', '--no-asm','--threads',  '--seek',
    '--partitions', '--direct', '--no-weightb', '--weightp', '--me',
    '--merange', '--mvrange', '--subme', '--psy-rd', '--no-psy', '--no-mixed-refs', '--no-chroma-me',
    '--no-8x8dct', '--trellis', '--no-fast-pskip', '--no-dct-decimate', '--nr', '--deadzone-inter', '--deadzone-intra', '--cqm']
    # '--profile', '--cqmfile', '--cqm4', '--cqm8', '--cqm4i', '--cqm4iy',
    # '--overscan', '--videoformat', '--range', '--colorprim', '--transfer',
    # '--colormatrix', '--chromaloc', '--alternative-transfer', '--nal-hrd', '--filler', '--pic-struct', '--crop-rect',]
    # '--muxer',
    # '--demuxer', '--input-fmt', '--input-csp', '--output-csp', '--input-depth', '--output-depth', '--input-range', '--input-res', '--index',
    # '--sar', '--fps', '--frames', '--level', '--bluray-compat',  '--avcintra-flavor', '--stitchable', '--verbose',
    # '--no-progress', '--quiet', '--log-level', '--psnr', '--ssim', '--lookahead-threads', '--sliced-threads', '--thread-input',
    # '--sync-lookahead', '--non-deterministic', '--cpu-independent', '--asm', '--opencl', '--opencl-clbin', '--opencl-device',
    # '--dump-yuv', '--sps-id', '--aud', '--force-cfr', '--tcfile-in', '--tcfile-out', '--dts-compress', '--vf', '--qpfile', '--vbv-maxrate', '--vbv-bufsize',
    #'--vbv-init', '--preset', '--tune', '--slow-firstpass',]

    #'--time_base'
    #'--avcintra-class',
x264_arg_dic = {
         '--keyint':['range_integer', '1', '500'],'--min-keyint': ['range_integer', '1', '500'], '--scenecut': ['range_integer', '1', '300'],
         '--bframes': ['range_integer', '1', '300'], '--b-adapt': ['0','1','2'], '--b-bias': ['range_integer', '-100', '100'],
         '--b-pyramid': ['none', 'strict', 'normal'], '--ref': ['range_integer', '1', '20'], '--deblock': ['alpha:beita'],
         '--slices': ['range_integer', '0', '8'], '--slices-max': ['range_integer', '0', '8'],
         '--slice-max-size': ['range_integer', '0', '8'], '--slice-max-mbs': ['range_integer', '0', '8'],
         '--slice-min-mbs': ['range_integer', '0', '8'], '--pulldown': ['none', '22', '32', '64', 'double', 'triple', 'euro'],
         '--frame-packing': ['0','1','2','3','4','5','6','7'], '--qp': ['range_integer', '0', '81'],
         '--bitrate': ['range_integer', '1', '2000'], '--crf': ['range_float', '-12.0', '51.0'],
         '--rc-lookahead': ['range_integer', '1', '250'],'--crf-max': ['range_float', '30.0', '100.0'], '--qpmin': ['range_integer', '1', '30'],
         '--qpmax': ['range_integer', '30', '80'], '--qpstep': ['range_integer', '1', '10'],
         '--ratetol': ['range_float', '0.1', '100.0'], '--ipratio': ['range_float', '0', '5'],
         '--pbratio': ['range_float', '0', '5'], '--chroma-qp-offset': ['range_integer', '-10', '10'], '--aq-mode': ['0', '1', '2', '3'],
         '--aq-strength': ['range_float', '0', '25'], '--pass': ['1', '2', '3'],
         '--stats': ["x264_2pass.log"], '--qcomp': ['range_float', '0', '1'], '--cplxblur': ['range_float', '1', '40'],
         '--qblur': ['range_float', '-1', '2'], '--zones': ['zone'], '--threads': ['range_integer', '0', '300'],
         '--seek': ['range_integer', '0', '1000'],
         '--partitions': ['p8x8', 'p4x4', 'b8x8', 'i8x8', 'i4x4', 'none', 'all'], '--direct': ['none', 'spatial', 'temporal', 'auto'],
         '--weightp': ['0', '1', '2'], '--me': ['dia', 'hex', 'umh', 'esa', 'tesa'], '--merange': ['range_integer', '1', '64'],
         '--mvrange': ['range_integer', '1', '512'], '--subme': ['range_integer', '0', '11'],
         '--trellis': ['0', '1', '2'], '--nr': ['range_integer', '100', '1000'], '--psy-rd': ['float:float'], '--deadzone-inter': ['range_integer', '0', '32'],
         '--deadzone-intra': ['range_integer', '0', '32'], '--cqm': ['flat', 'jvt']}
         # '--profile': ['baseline', 'main', 'high', 'high10', 'high422', 'high444'], '--cqmfile': [], '--cqm4': [], '--cqm8': [],
         # '--cqm4i': [], '--cqm4iy': [],
         # '--preset': ['ultrafast', 'superfast', 'veryfast', 'faster', 'fast', 'medium', 'slow', 'slower', 'veryslow', 'placebo'],
         # '--tune': ['film', 'animation', 'grain', 'stillimage', 'psnr', 'ssim', 'fastdecode', 'zerolatency'],
         # '--overscan': ['undef', 'show', 'crop'],
         # '--videoformat': ['component', 'pal', 'ntsc', 'secam', 'mac', 'undef'], '--range': ['auto', 'tv', 'pc'],
         # '--colorprim': ['undef', 'bt709', 'bt470m', 'bt470bg', 'smpte170m', 'smpte240m', 'film', 'bt2020', 'smpte428', 'smpte431', 'smpte432'],
         # '--transfer': ['undef', 'bt709', 'bt470m', 'bt470bg', 'smpte170m', 'smpte240m', 'linear', 'log100', 'log316', 'iec61966-2-4', 'bt1361e', 'iec61966-2-1', 'bt2020-10', 'bt2020-12', 'smpte2084', 'smpte428', 'arib-std-b67'],
         # '--colormatrix': ['undef', 'bt709', 'fcc', 'bt470bg', 'smpte170m', 'smpte240m', 'GBR', 'YCgCo', 'bt2020nc', 'bt2020c', 'smpte2085', 'chroma-derived-nc', 'chroma-derived-c', 'ICtCp'],
         # '--chromaloc': ['range_integer', '0', '5'], '--sar':['width:height'], '--qpfile': [],
         # '--alternative-transfer': ['undef', 'bt709', 'bt470m', 'bt470bg', 'smpte170m', 'smpte240m', 'linear', 'log100', 'log316', 'iec61966-2-4', 'bt1361e','iec61966-2-1', 'bt2020-10', 'bt2020-12', 'smpte2084', 'smpte428', 'arib-std-b67'],
         # '--nal-hrd': ['none', 'vbr', 'cbr'], '--crop-rect': []}
        # '--muxer': ['auto', 'raw', 'mkv', 'flv'], '--demuxer': ['auto', 'raw', 'y4m', 'avs'], '--input-fmt': [],
         # '--input-csp': ['i400', 'i420', 'yv12', 'nv12', 'nv21', 'i422', 'yv16', 'nv16', 'yuyv', 'uyvy', 'i444', 'yv24', 'bgr', 'bgra', 'rgb'],
         # '--output-csp': ['i420'], '--input-depth': ['any_integer'], '--output-depth': [], '--input-range': ['auto', 'tv', 'pc'], '--input-res': ['intxint'], '--index': [],
         # , '--fps': ['float|rational'], '--frames': ['any_integer'], '--level': [], '--avcintra-flavor': ['panasonic', 'sony'], '--log-level': [], ,
         # '--lookahead-threads': [], '--sync-lookahead': [], '--asm': [], '--opencl-clbin': [], '--opencl-device': [], '--dump-yuv': [],
         # '--sps-id': [], '--tcfile-in': [], '--tcfile-out': [], '--vf': [], '--vbv-maxrate': ['any_integer'], '--vbv-bufsize': ['any_integer'],
         #'--vbv-init': ['any_float']}
                #'--output-csp': ['i400', 'i420', 'i422', 'i444', 'rgb']
                #'--timebase': ['any_integer']
                #'--avcintra-class': ['50', '100', '200'],